### ISSUE TITLE
Add Service Registry Endpoints

### ISSUE THREAD

**Issue by thclark** [octue/django-twined#49]
# Feature request

## Use Case

I am running `service-a` which has received a question. `service-a` has a child, `service-b`. Every time I update `service-b`, I have to update `service-a` in order to use the latest version.

When a new `service-b` version is released, I want to add it to a `Service Registry` (eg a django server with django-twined installed so it has a table of service revisions). Then, I want `service-a` to call an endpoint on the Service Registry, to discover which version of `service-b` to use and where it resides.

In future, we want the Service Registry to also be able to:
- Act as a permission gateway (eg 'yes, you have paid for access to this / have permission to ask questions, here's a signed token to prove it')
- Tell the querying service how to invoke the question. 
  - eg At the moment we work exclusively through GCP pubsub, so the querying service would have to have service account credentials sufficient for asking questions.
  - eg in the future maybe we want to simply expose an endpoint so services outside our own infrastructure can ask questions of our internal services.
  - Detect compatible versions: can we ask for a semantic version range? eg `octue/our-service:^0.1.2`

In future, we probably want to run a 'default' service registry as Octue. So someone could have a couple of their own private services with their own registry, but then fall back to the octue registry by default. So when defining the service registry endpoint, do it in an array so we can iterate through (like with private registries for python packages).

## Current state

The `app_configuration.json` file in `service_a` contains a `children` property that defines the SRUID (`octue/service-b:0.1.2`) of the child service. This `app_configuration.json` must thus be updated, and `service-a` released with a new version, every time `service-b` changes. The updates casade: everything relying on `service-a` must then **also** be changed.

### In django-twined

**nb namespace is not necessarily unique for a registry**

- [x] Add views to expose basic `GET` and `POST` endpoints, eg:
  - **To determine exactly what version of a service whose name and namespace you know**
    - [x] `GET registry-domain.com/<developer-chooses-url-pattern>/services/<namespace>/<name>?revision-tag=<optional-version-range-eg^0.1.2>`
    - *Note for marcus - you can leave out the version range functionality for now and just always return the default but create an issue to come back to this*
    - [x] Return something like:
    ```json
     {"namespace": "myorg", "name": "myname", "revision_tag": "0.1.3", } 
    ```
  - Later we can add somehting like: `"backend": {"type": "gcp-pubsub", "project": the-project"}` but that's not needed yet.
  - **To register a new service release**
    - [x] `POST registry-domain.com/<developer-chooses-url-pattern>/services/<namespace>/<name>`
    - [x] With body like:
      ```json
       {"namespace": "myorg", "name": "myname", "revision_tag": "0.1.3"} 
     ```

- [x] Use basic JSON views rather htan relying on DRF
- [x] Add to the docs / instructions how to add that view. [django-gcp](https://django-gcp.readthedocs.io/en/latest/getting_started.html#add-the-endpoints) does a similar thing with events endpoints, it creates a view then instructs the developer of the django app how to add them.

### In services (the octue-sdk)

- [x] We should be able to define, in `octue.yaml`, which service registry we want to use in order to fetch the `children`.
  So if in `service-a`, the `octue.yaml` file looked like this:
  ```yml
  service_registries: 
    - name: MyOrg Registry  # For our private internal services
      endpoint: api.myorg.com/integrations/octue/service-registry
    - name: Octue Registry  # Fallback to publicly available services
      endpoint: services.registry.octue.com
  ```

**Comment by cortadocodes** [comment]
To be explicit, another thing needed in the SDK: 
- [ ] `Service.ask` needs to use the registries defined in `octue.yaml` to get the SRUID to ask a question to iff the service revision tag isn't provided

**Comment by cortadocodes** [comment]
Questions:
- [ ] Do we still want to keep the `is_default` concept in django-twined?
- [ ] Project name is currently a field in ServiceRevision model - given that, should I allow it to be specified during post and got during get?

**Comment by cortadocodes** [comment]
@thclark I just remembered when we first discussed this you wanted to allow additional service revision selection criteria based on the question UUID - could you provide some more detail if you'd still like that added?
