### ISSUE TITLE
Decide whether to remove ReelMessage and websocket functionality

### ISSUE THREAD

**Issue by thclark** [octue/django-twined#58]
### Status

ReelMessage is ancient (pre `octue` 0.16!) and won't work at all with current `octue` messaging protocol so should be removed.

However, its purpose is to demonstrate the use of django-tiwned to stream octue events (which later became service usage events) over a websocket, using django-channels.

The latter aspect worked successfully and so I'm uninclined to simply delete all code, because it's something that could realistically be required in future. We should probably remove all code, but keep the setup (eg by referencing a tag) for posterity when we come to implement websockets.

It may very well be that we never implement sockets within django-twined (and similar arguments exist surrounding subscribable graphql endpoints) and instead simply provide demonstrators for how to achieve that.

**Comment by thclark** [comment]
Decision: after investigation of how to implement the sockets funcitonality, yes we WILL remove this.

**Comment by cortadocodes** [comment]
See #64
